version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    container_name: dse_learn_lab_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dse_learn_lab
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dse_learn_lab_web
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/dse_learn_lab
    volumes:
      - ./backend:/code
    depends_on:
      - db

volumes:
  postgres_data:
